Repository Seagate/cortx-utils, pull requests merged in 2022-08, with the labels that each got.

#837 CORTX-32168: Added Codeowner for Utils
  .github/auto_assign.yml
Labels: Status: Waiting to be Merged

#869 CORTX-33673: Improvement for lock-unlock interface with lock end time…
  py-utils/src/utils/conf_store/conf_store.py
  py-utils/src/utils/const.py
  py-utils/test/conf_store/conf_store_multiple_lock_threads_test.py
Labels: Status: Waiting to be Reviewed

#870 CORTX-33856: str to dict in topology
  py-utils/src/utils/query_deployment/query_deployment.py
Labels: Status: Changes Requested
